### ISSUE TITLE
Song Files

### ISSUE THREAD

**Issue by danielyx-z** [RedNotSus/lofi-radio#1]
Hello!

I really liked the songs you've chosen for this project. Is there any way I can find a collection of them for local use?

Thanks!

**Comment by jiayangc1** [comment]
hi!

thanks i just downloaded them from this playlist: https://open.spotify.com/playlist/679wCT6dVMDBxrYa5NcrXL?si=ae191f3d7df647e8

I used https://spotifydown.com/

**Comment by danielyx-z** [comment]
Thanks!

**Comment by ghost** [comment]
hey red do you like spotify or apple music more
